version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.11
    container_name: rabbitmq
    ports:
      - 5672:5672
  app:
    build: .
    container_name: app
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
    volumes:
      - ./:/app
