version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.11
    container_name: rabbitmq
    ports:
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  app:
    build: .
    container_name: app
    ports:
      - 8000:8000
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./:/app
    command: ["sh", "-c", "cd /app && python -u src/main.py"]
